function alpha_sol = bh_alpha_func(L_1,L_2,L_3,L_4,theta,phi)
%BH_ALPHA_FUNC
%    ALPHA_SOL = BH_ALPHA_FUNC(L_1,L_2,L_3,L_4,THETA,PHI)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    30-Sep-2019 08:28:03

alpha_sol = atan2(L_3.*sin(phi)-L_1.*sin(theta),L_4+L_3.*cos(phi)-L_1.*cos(theta));
