function phi_sol_2 = bh_phi_2_func(L_1,L_2,L_3,L_4,theta)
%BH_PHI_2_FUNC
%    PHI_SOL_2 = BH_PHI_2_FUNC(L_1,L_2,L_3,L_4,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    30-Sep-2019 08:28:03

t2 = cos(theta);
t3 = L_1.^2;
t4 = L_2.^2;
t5 = L_3.^2;
t6 = L_4.^2;
t7 = L_2.*L_3.*2.0;
t8 = -t4;
t9 = L_1.*L_4.*t2.*2.0;
t10 = -t9;
phi_sol_2 = atan2(-sqrt((t3-t5+t6+t7+t8+t10).*(-t3+t4+t5-t6+t7+t9))+L_1.*L_3.*sin(theta).*2.0,t3+t5+t6+t8+t10-L_3.*L_4.*2.0+L_1.*L_3.*t2.*2.0).*2.0;
