function [the_z,the_num,the_den] = bh_z_func(L_1,L_2,L_3,L_4,theta)
%BH_Z_FUNC
%    [THE_Z,THE_NUM,THE_DEN] = BH_Z_FUNC(L_1,L_2,L_3,L_4,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    30-Sep-2019 08:28:02

t2 = cos(theta);
t3 = sin(theta);
t4 = L_1.^2;
t5 = L_2.^2;
t6 = L_3.^2;
t7 = L_4.^2;
t8 = L_2.*L_3.*2.0;
t9 = L_3.*L_4.*2.0;
t10 = -t9;
t11 = -t4;
t12 = -t5;
t13 = -t6;
t14 = -t7;
t15 = L_1.*L_3.*t2.*2.0;
t16 = L_1.*L_4.*t2.*2.0;
t17 = L_1.*L_3.*t3.*2.0;
t18 = -t16;
t19 = t5+t6+t8+t11+t14+t16;
t20 = t4+t7+t8+t12+t13+t18;
t21 = t4+t6+t7+t10+t12+t15+t18;
t22 = 1.0./t21;
t23 = t19.*t20;
t24 = sqrt(t23);
t25 = t17+t24;
the_z = [t22.*t25;t22.*(t17-t24)];
if nargout > 1
    the_num = [t25;t17-t24];
end
if nargout > 2
    the_den = [t21;t21];
end
