function yB_SYM_sol = tmp_mlf_yB(L1,L2,L3,L4,xA,yA)
%TMP_MLF_YB
%    YB_SYM_SOL = TMP_MLF_YB(L1,L2,L3,L4,XA,YA)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Nov-2019 16:26:42

t2 = L2.^2;
t3 = L3.^2;
t4 = L4.^2;
t5 = xA.^2;
t6 = yA.^2;
t7 = yA.^3;
t8 = L4.*xA.*2.0;
t9 = L2.*L3.*2.0;
t21 = L4.*xA.*yA.*-2.0;
t10 = -t8;
t11 = t2.*yA;
t12 = t3.*yA;
t13 = t4.*yA;
t14 = t8.*yA;
t15 = t5.*yA;
t16 = -t2;
t17 = -t3;
t18 = -t4;
t19 = -t5;
t20 = -t6;
t22 = -t11;
t23 = t4+t5+t6+t10;
t26 = t2+t3+t8+t9+t18+t19+t20;
t24 = 1.0./t23;
t25 = t9+t16+t17+t23;
t27 = t25.*t26;
t28 = sqrt(t27);
t29 = L4.*t28;
t30 = t28.*xA;
yB_SYM_sol = [(t24.*(t7+t12+t13+t15+t21+t22-t29+t30))./2.0;(t24.*(t7+t12+t13+t15+t21+t22+t29-t30))./2.0];
