function xB_SYM_sol = tmp_mlf_xB(L1,L2,L3,L4,xA,yA)
%TMP_MLF_XB
%    XB_SYM_SOL = TMP_MLF_XB(L1,L2,L3,L4,XA,YA)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Nov-2019 16:26:42

t2 = L2.^2;
t3 = L3.^2;
t4 = L4.^2;
t5 = L4.^3;
t6 = xA.^2;
t7 = xA.^3;
t8 = yA.^2;
t9 = L4.*xA.*2.0;
t10 = L2.*L3.*2.0;
t11 = -t9;
t12 = L4.*t2;
t13 = L4.*t3;
t14 = t2.*xA;
t15 = t3.*xA;
t16 = L4.*t6;
t17 = t4.*xA;
t18 = L4.*t8;
t19 = t8.*xA;
t20 = -t2;
t21 = -t3;
t22 = -t4;
t23 = -t6;
t24 = -t8;
t25 = -t13;
t26 = -t14;
t27 = -t16;
t28 = -t17;
t29 = t4+t6+t8+t11;
t32 = t2+t3+t9+t10+t22+t23+t24;
t30 = 1.0./t29;
t31 = t10+t20+t21+t29;
t33 = t31.*t32;
t34 = sqrt(t33);
t35 = t34.*yA;
xB_SYM_sol = [(t30.*(t5+t7+t12+t15+t18+t19+t25+t26+t27+t28-t35))./2.0;(t30.*(t5+t7+t12+t15+t18+t19+t25+t26+t27+t28+t35))./2.0];
